BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS server (id INTEGER PRIMARY KEY,);

CREATE TABLE IF NOT EXISTS category (id INTEGER NOT NULL, serverid INTEGER NOT NULL, PRIMARY KEY (id, serverId));

CREATE TABLE IF NOT EXISTS channelSettings (id INTEGER PRIMARY KEY);
CREATE TABLE IF NOT EXISTS voiceChannel (id INTEGER NOT NULL, categoryId INTEGER NOT NULL, channelSettingsId, PRIMARY KEY (id, categoryId));
CREATE TABLE IF NOT EXISTS role (id INTEGER PRIMARY KEY);

CREATE TABLE IF NOT EXISTS channel_role (voiceChannelId INTEGER, roleId INTEGER);
CREATE TABLE IF NOT EXISTS category_role (voiceChannelId INTEGER, roleId INTEGER);

COMMIT;